### ISSUE TITLE
java.lang.UnsatisfiedLinkError on Win10 system

### ISSUE THREAD

**Issue by dancencheung** [nintha/webp-imageio-core#10]
I learned that I do not need to load webp*.dll by myself to handle webp image by webp-imageio-core. So in my project, I use webp-imageio-core-0.1.3.jar to convert image to webp format, but the error happened.
I tried webp-imageio-core-0.1.2.jar and webp-imageio-core-0.1.1.jar, the error is same. but when I tried webp-imageio-core-0.1.0.jar, it worked. my system is Windows 10 64bit.
So what's the problem, just webp-imageio-core-0.1.0.jar worked for Win10?

Error:

`十月 31, 2019 5:28:51 下午 org.scijava.nativelib.NativeLibraryUtil loadNativeLibrary
警告: Problem with library
java.lang.UnsatisfiedLinkError: C:\Users\zhangdan\AppData\Local\Temp\webp-imageio4585631737438415528.dll: Can't find dependent libraries
	at java.lang.ClassLoader$NativeLibrary.load(Native Method)
	at java.lang.ClassLoader.loadLibrary0(Unknown Source)
	at java.lang.ClassLoader.loadLibrary(Unknown Source)
	at java.lang.Runtime.load0(Unknown Source)
	at java.lang.System.load(Unknown Source)
	at org.scijava.nativelib.NativeLibraryUtil.loadNativeLibrary(NativeLibraryUtil.java:291)
	at com.luciad.imageio.webp.WebP.loadNativeLibrary(WebP.java:29)
	at com.luciad.imageio.webp.WebP.<clinit>(WebP.java:34)
	at com.luciad.imageio.webp.WebPEncoderOptions.<clinit>(WebPEncoderOptions.java:20)
	at com.luciad.imageio.webp.WebPWriteParam.<init>(WebPWriteParam.java:30)
	at com.luciad.imageio.webp.WebPWriter.getDefaultWriteParam(WebPWriter.java:38)
	at com.luciad.imageio.webp.WebPWriter.write(WebPWriter.java:64)
	at javax.imageio.ImageWriter.write(Unknown Source)
	at javax.imageio.ImageIO.doWrite(Unknown Source)
	at javax.imageio.ImageIO.write(Unknown Source)
	at com.dancen.util.image.MyImageHelper.writeBufferedImage(MyImageHelper.java:517)
	at com.dancen.util.image.MyImageHelper.writeBufferedImage(MyImageHelper.java:481)
	at com.dancen.util.image.MyImageFormatUtil.convert(MyImageFormatUtil.java:61)
	at com.dancen.util.image.MyImageFormatUtil.convert(MyImageFormatUtil.java:34)
	at com.dancen.util.image.MyImageFormatUtil.main(MyImageFormatUtil.java:22)

Exception in thread "main" java.lang.UnsatisfiedLinkError: com.luciad.imageio.webp.WebPEncoderOptions.createConfig()J
	at com.luciad.imageio.webp.WebPEncoderOptions.createConfig(Native Method)
	at com.luciad.imageio.webp.WebPEncoderOptions.<init>(WebPEncoderOptions.java:26)
	at com.luciad.imageio.webp.WebPWriteParam.<init>(WebPWriteParam.java:30)
	at com.luciad.imageio.webp.WebPWriter.getDefaultWriteParam(WebPWriter.java:38)
	at com.luciad.imageio.webp.WebPWriter.write(WebPWriter.java:64)
	at javax.imageio.ImageWriter.write(Unknown Source)
	at javax.imageio.ImageIO.doWrite(Unknown Source)
	at javax.imageio.ImageIO.write(Unknown Source)
	at com.dancen.util.image.MyImageHelper.writeBufferedImage(MyImageHelper.java:517)
	at com.dancen.util.image.MyImageHelper.writeBufferedImage(MyImageHelper.java:481)
	at com.dancen.util.image.MyImageFormatUtil.convert(MyImageFormatUtil.java:61)
	at com.dancen.util.image.MyImageFormatUtil.convert(MyImageFormatUtil.java:34)
	at com.dancen.util.image.MyImageFormatUtil.main(MyImageFormatUtil.java:22)`

**Comment by nintha** [comment]
This may be a compatibility issue. I compiled the dll file in Windows 10 version 1903 build 18945.

You can compile it by yourself. [compiling-the-native-library](https://github.com/nintha/webp-imageio-core#compiling-the-native-library)

**Comment by francm** [comment]
@nintha Your windows dll was built with debug symbols and debug dependencies. Better way should be statically linked deps. I will try my static build next week with a few colleagues. I will let you know.
