### ISSUE TITLE
java.lang.UnsatisfiedLinkError

### ISSUE THREAD

**Issue by shuqiyige** [nintha/webp-imageio-core#15]
六月 29, 2020 2:11:59 下午 org.scijava.nativelib.NativeLibraryUtil loadNativeLibrary
警告: Problem with library
java.lang.UnsatisfiedLinkError: C:\Users\shuqi\AppData\Local\Temp\webp-imageio5936908501753317424.dll: Can't find dependent libraries
	at java.lang.ClassLoader$NativeLibrary.load(Native Method)
	at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1941)
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1824)
	at java.lang.Runtime.load0(Runtime.java:809)
	at java.lang.System.load(System.java:1086)
	at org.scijava.nativelib.NativeLibraryUtil.loadNativeLibrary(NativeLibraryUtil.java:291)
	at com.luciad.imageio.webp.WebP.loadNativeLibrary(WebP.java:29)
	at com.luciad.imageio.webp.WebP.<clinit>(WebP.java:34)
	at com.luciad.imageio.webp.WebPDecoderOptions.<clinit>(WebPDecoderOptions.java:20)
	at com.luciad.imageio.webp.WebPReadParam.<init>(WebPReadParam.java:24)
	at example.DecodeTest.main(DecodeTest.java:23)

**Comment by nintha** [comment]
This project just wrap java code and dll files. You may go to source repo [luciad/webp-imageio](https://bitbucket.org/luciad/webp-imageio) , and create issue about UnsatisfiedLinkError .
