### ISSUE TITLE
java.lang.UnsatisfiedLinkError: com.luciad.imageio.webp.WebPEncoderOptions.createConfig

### ISSUE THREAD

**Issue by uzhy1987** [nintha/webp-imageio-core#16]
java.lang.UnsatisfiedLinkError: com.luciad.imageio.webp.WebPEncoderOptions.createConfig()J
        at com.luciad.imageio.webp.WebPEncoderOptions.createConfig(Native Method)
        at com.luciad.imageio.webp.WebPEncoderOptions.<init>(WebPEncoderOptions.java:26)
        at com.luciad.imageio.webp.WebPWriteParam.<init>(WebPWriteParam.java:30)

**Comment by nintha** [comment]
This project just wrap java code and dll files. You may go to source repo [luciad/webp-imageio](https://bitbucket.org/luciad/webp-imageio) , and create issue about UnsatisfiedLinkError .
