### ISSUE TITLE
Error while loading : Can't find dependent libraries

### ISSUE THREAD

**Issue by jobartim44** [nintha/webp-imageio-core#17]
While trying to test the library under Windows I have the folowing error. The  webp-imageio.dll is in the temporary directory but it seems that there are dependent libraries...

Can someone help me ?

```
déc. 11, 2020 7:20:51 PM org.scijava.nativelib.NativeLibraryUtil loadNativeLibrary
AVERTISSEMENT: Problem with library
java.lang.UnsatisfiedLinkError: C:\Users\pnv_vmo.ASP\AppData\Local\Temp\webp-imageio3809737815982273834.dll: Can't find dependent libraries
	at java.lang.ClassLoader$NativeLibrary.load(Native Method)
	at java.lang.ClassLoader.loadLibrary1(ClassLoader.java:1965)
	at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1890)
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1851)
	at java.lang.Runtime.load0(Runtime.java:795)
	at java.lang.System.load(System.java:1062)
	at org.scijava.nativelib.NativeLibraryUtil.loadNativeLibrary(NativeLibraryUtil.java:291)
	at com.luciad.imageio.webp.WebP.loadNativeLibrary(WebP.java:29)
	at com.luciad.imageio.webp.WebP.<clinit>(WebP.java:34)
	at com.luciad.imageio.webp.WebPEncoderOptions.<clinit>(WebPEncoderOptions.java:20)
	at com.luciad.imageio.webp.WebPWriteParam.<init>(WebPWriteParam.java:30)
	at example.EncodeTest.main(EncodeTest.java:26)
```

**Comment by Ero-Cat** [comment]
![image](https://user-images.githubusercontent.com/11071219/105865909-596cd980-602e-11eb-83cb-5ac332e69e45.png)
me too.

**Comment by Ero-Cat** [comment]
> ![image](https://user-images.githubusercontent.com/11071219/105865909-596cd980-602e-11eb-83cb-5ac332e69e45.png)
> me too.

just  windows not work

**Comment by Renwq** [comment]
me too

**Comment by Ero-Cat** [comment]
> me too

别用maven ,使用jar包导入试试

**Comment by graycatdeveloper** [comment]
i too

**Comment by devifish** [comment]
Windows平台的dll， 作者使用了VS2017的DEBUG模式下编译的依赖VCRUNTIME140D.dll

**Comment by RavenLiao** [comment]
me too, but solve by use [v0.1.0](https://jitpack.io/#nintha/webp-imageio-core/v0.1.0)
而且提过类似的问题了：https://github.com/nintha/webp-imageio-core/issues/2

**Comment by Aismy** [comment]
> > me too
> 
> 别用maven ,使用jar包导入试试

你的正常了吗

**Comment by egloffmark** [comment]
I had the same issue on a Windows 10 System. I solved this by analyzing and installing the missing dll dependencies of the temporary "webp-imageio.dll". In my case the following dependencies have been missing. So I put these into "C:\Windows\System32" directory:
- vcruntime140d.dll
- ucrtbased.dll

Tool to analyze the DLL dependencies on Windows:
- https://lucasg.github.io/Dependencies/  => start then the "DependenciesGui.exe" and drag and drop the dll file which you like to  have analyzed

to get  vcruntime140 you need to download Microsoft Visual C++ Redistributable Version
https://learn.microsoft.com/en-us/cpp/windows/latest-supported-vc-redist?view=msvc-170#visual-studio-2015-2017-2019-and-2022 or https://aka.ms/vs/17/release/vc_redist.x64.exe  this should then automatically install the library on your windows system and no copy to system32 folder should be necessary 
*Remark:* I had to rename the "vcruntime140.dll" simple to "vcruntime140d.dll" don't ask me why. The "d" version is the debug version. However I assume the trick by renaming it may do it. 

For the "ucrtbased.dll" you need to get the VS2022 Community installed. https://visualstudio.microsoft.com/downloads/ or Windows SDK download https://developer.microsoft.com/en-us/windows/downloads/sdk-archive/ it get then for instance installed into C:\Program Files (x86)\Windows Kits\10\bin\10.0.22621.0\x64\ucrt\ucrtbased.dll this then you can copy to your "System32" directory 

![image](https://github.com/nintha/webp-imageio-core/assets/7382336/6ecd3d0c-0df3-47b4-80df-965c66ca9291)
